apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-container
        image: us-central1-docker.pkg.dev/mlops-project-491208/ml-repo/ml-project:latest
        ports:
        - containerPort: 5000